const Items = [
  {
    itemName: 'Chardonnay',
    numberCategory: 1,
    itemCategory: 'Branco',
    itemPrice: 'R$ 260,00',
    itemSigns: '4.5',
    ml: '750ml',
    itemDescription: 'Vinho branco encorpado com notas de frutas tropicais e toques de baunilha.',
    imageSource: require('../assets/home/chardonnay.png'),
    itemSold: 0,
  },
  {
    itemName: 'Sauvignon Blanc',
    numberCategory: 1,
    itemCategory: 'Branco',
    itemPrice: 'R$ 109,00',
    itemSigns: '4.8',
    ml: '750ml',
    itemDescription: 'Vinho fresco, cítrico, e herbáceo, ideal para refeições leves.',
    imageSource: require('../assets/home/sauvignon_blanc.png'),
    itemSold: 0,
  },
  {
    itemName: 'Riesling',
    numberCategory: 1,
    itemCategory: 'Branco',
    itemPrice: 'R$ 155,00',
    itemSigns: '4.3',
    ml: '750ml',
    itemDescription: 'Branco aromático, com leve dulçor e acidez vibrante.',
    imageSource: require('../assets/home/riesling.png'),
    itemSold: 0,
  },
  {
    itemName: 'Pinot Grigio',
    numberCategory: 1,
    itemCategory: 'Branco',
    itemPrice: 'R$ 220,00',
    itemSigns: '4.0',
    ml: '750ml',
    itemDescription: 'Vinho leve e refrescante, com toques cítricos e minerais.',
    imageSource: require('../assets/home/pinot_grigio.png'),
    itemSold: 0,
  },
  {
    itemName: 'Provence Rosé',
    numberCategory: 2,
    itemCategory: 'Rosé',
    itemPrice: 'R$ 328,00',
    itemSigns: '4.7',
    ml: '750ml',
    itemDescription: 'Refrescante, com notas de frutas vermelhas e florais.',
    imageSource: require('../assets/home/provence_rose.png'),
    itemSold: 0,
  },
  {
    itemName: 'White Zinfandel',
    numberCategory: 2,
    itemCategory: 'Rosé',
    itemPrice: 'R$ 540,00',
    itemSigns: '4.2',
    ml: '750ml',
    itemDescription: 'Levemente adocicado, com frutas vermelhas e acidez sutil.',
    imageSource: require('../assets/home/white_zinfandel.png'),
    itemSold: 0,
  },
  {
    itemName: 'Cabernet Sauvignon',
    numberCategory: 3,
    itemCategory: 'Tinto',
    itemPrice: 'R$ 88,00',
    itemSigns: '4.6',
    ml: '750ml',
    itemDescription: 'Tinto encorpado, com notas de frutas escuras e taninos marcantes.',
    imageSource: require('../assets/home/cabernet_sauvignon.png'),
    itemSold: 0,
  },
  {
    itemName: 'Merlot',
    numberCategory: 3,
    itemCategory: 'Tinto',
    itemPrice: 'R$ 298,00',
    itemSigns: '4.1',
    ml: '750ml',
    itemDescription: 'Macio e elegante, com toques de ameixa e chocolate.',
    imageSource: require('../assets/home/merlot.png'),
    itemSold: 0,
  },
  {
    itemName: 'Prosecco',
    numberCategory: 4,
    itemCategory: 'Espumante',
    itemPrice: 'R$ 65,00',
    itemSigns: '4.4',
    ml: '750ml',
    itemDescription: 'Espumante leve, com notas de pêssego e maçã verde.',
    imageSource: require('../assets/home/prosecco.png'),
    itemSold: 0,
  },
  {
    itemName: 'Champagne',
    numberCategory: 4,
    itemCategory: 'Espumante',
    itemPrice: 'R$ 270,00',
    itemSigns: '4.9',
    ml: '750ml',
    itemDescription: 'Clássico espumante francês, com sabor complexo e final elegante.',
    imageSource: require('../assets/home/champagne.png'),
    itemSold: 0,
  },
];

export default Items;