const Wines = [    
    {
      wineName: 'Les Légends Bordeaux Rouge',
      wineCategory: 'Bordeaux',
      winePrice: 'R$ 260,00',
      wineSigns: '4.5',
      ml: '750ml',
      wineDescription: 'Um vinho equilibrado e robusto, com notas de frutas vermelhas.',
      imageSource: require('../assets/home/vinho1.png'),
      wineSold: 123,
    },
    {
      wineName: 'Cazauvielho Bordeaux',
      wineCategory: 'Bordeaux',
      winePrice: 'R$ 109,00',
      wineSigns: '4.8',
      ml: '750ml',
      wineDescription: 'Vinho jovem e frutado, ideal para refeições leves.',
      imageSource: require('../assets/home/vinho2.png'),
      wineSold: 136,
    },
    {
      wineName: 'Château Pitron Bordeaux',
      wineCategory: 'Bordeaux',
      winePrice: 'R$ 155,00',
      wineSigns: '4.3',
      ml: '750ml',
      wineDescription: 'Corpo médio com taninos macios e um final suave.',
      imageSource: require('../assets/home/vinho3.png'),
      wineSold: 174,
    },
    {
      wineName: 'Château Margaux Bordeaux',
      wineCategory: 'Bordeaux',
      winePrice: 'R$ 2200,00',
      wineSigns: '4.0',
      ml: '750ml',
      wineDescription: 'Vinho icônico, de complexidade impressionante e notas florais.',
      imageSource: require('../assets/home/vinho4.png'),
      wineSold: 87,
    },
    {
      wineName: 'Borgonha Blanc',
      wineCategory: 'Borgonha Branco',
      winePrice: 'R$ 328,00',
      wineSigns: '4.7',
      ml: '750ml',
      wineDescription: 'Elegante e refrescante, com toques de frutas cítricas.',
      imageSource: require('../assets/home/borgonha_blanc.png'),
      wineSold: 24,
    },
    {
      wineName: 'Borgonha Chablis',
      wineCategory: 'Borgonha Branco',
      winePrice: 'R$ 540,00',
      wineSigns: '4.2',
      ml: '750ml',
      wineDescription: 'Mineralidade marcante e acidez vibrante, perfeito para frutos do mar.',
      imageSource: require('../assets/home/borgonha_chablis.png'),
      wineSold: 72,
    },
    {
      wineName: 'Tinto Paulo Laureano',
      wineCategory: 'Tinto Português',
      winePrice: 'R$ 88,00',
      wineSigns: '4.6',
      ml: '750ml',
      wineDescription: 'Vinho português com notas de ameixa e especiarias, fácil de beber.',
      imageSource: require('../assets/home/tinto_paulo_laureano.png'),
      wineSold: 51,
    },
    {
      wineName: 'Tinto Quinta do Noval',
      wineCategory: 'Tinto Português',
      winePrice: 'R$ 298,00',
      wineSigns: '4.1',
      ml: '750ml',
      wineDescription: 'Complexo e encorpado, com taninos robustos e um final longo.',
      imageSource: require('../assets/home/tinto_quinta_do_noval.png'),
      wineSold: 105,
    },
    {
      wineName: 'Zentas Chardonnay',
      wineCategory: 'Pasta',
      winePrice: 'R$ 65,00',
      wineSigns: '4.4',
      ml: '750ml',
      wineDescription: 'Leve e frutado, com notas de pêssego e um toque amanteigado.',
      imageSource: require('../assets/home/pasta_zentas_chardonnay.png'),
      wineSold: 126,
    },
    {
      wineName: 'Villa Antinori Rosso',
      wineCategory: 'Pasta',
      winePrice: 'R$ 270,00',
      wineSigns: '4.9',
      ml: '750ml',
      wineDescription: 'Vinho italiano rico, com notas de frutas maduras e um final suave.',
      imageSource: require('../assets/home/villa_antinori_rosso.png'),
      wineSold: 65,
    }
  ];

  export default Wines;