const Wines = [
  {
    wineName: 'Chardonnay',
    wineCategory: 'Branco',
    winePrice: 'R$ 260,00',
    wineSigns: '4.5',
    ml: '750ml',
    wineDescription: 'Vinho branco encorpado com notas de frutas tropicais e toques de baunilha.',
    imageSource: require('../assets/home/chardonnay.png'),
    wineSold: 123,
  },
  {
    wineName: 'Sauvignon Blanc',
    wineCategory: 'Branco',
    winePrice: 'R$ 109,00',
    wineSigns: '4.8',
    ml: '750ml',
    wineDescription: 'Vinho fresco, cítrico, e herbáceo, ideal para refeições leves.',
    imageSource: require('../assets/home/sauvignon_blanc.png'),
    wineSold: 136,
  },
  {
    wineName: 'Riesling',
    wineCategory: 'Branco',
    winePrice: 'R$ 155,00',
    wineSigns: '4.3',
    ml: '750ml',
    wineDescription: 'Branco aromático, com leve dulçor e acidez vibrante.',
    imageSource: require('../assets/home/riesling.png'),
    wineSold: 174,
  },
  {
    wineName: 'Pinot Grigio',
    wineCategory: 'Branco',
    winePrice: 'R$ 220,00',
    wineSigns: '4.0',
    ml: '750ml',
    wineDescription: 'Vinho leve e refrescante, com toques cítricos e minerais.',
    imageSource: require('../assets/home/pinot_grigio.png'),
    wineSold: 87,
  },
  {
    wineName: 'Provence Rosé',
    wineCategory: 'Rosé',
    winePrice: 'R$ 328,00',
    wineSigns: '4.7',
    ml: '750ml',
    wineDescription: 'Refrescante, com notas de frutas vermelhas e florais.',
    imageSource: require('../assets/home/provence_rose.png'),
    wineSold: 24,
  },
  {
    wineName: 'White Zinfandel',
    wineCategory: 'Rosé',
    winePrice: 'R$ 540,00',
    wineSigns: '4.2',
    ml: '750ml',
    wineDescription: 'Levemente adocicado, com frutas vermelhas e acidez sutil.',
    imageSource: require('../assets/home/white_zinfandel.png'),
    wineSold: 72,
  },
  {
    wineName: 'Cabernet Sauvignon',
    wineCategory: 'Tinto',
    winePrice: 'R$ 88,00',
    wineSigns: '4.6',
    ml: '750ml',
    wineDescription: 'Tinto encorpado, com notas de frutas escuras e taninos marcantes.',
    imageSource: require('../assets/home/cabernet_sauvignon.png'),
    wineSold: 51,
  },
  {
    wineName: 'Merlot',
    wineCategory: 'Tinto',
    winePrice: 'R$ 298,00',
    wineSigns: '4.1',
    ml: '750ml',
    wineDescription: 'Macio e elegante, com toques de ameixa e chocolate.',
    imageSource: require('../assets/home/merlot.png'),
    wineSold: 105,
  },
  {
    wineName: 'Prosecco',
    wineCategory: 'Espumante',
    winePrice: 'R$ 65,00',
    wineSigns: '4.4',
    ml: '750ml',
    wineDescription: 'Espumante leve, com notas de pêssego e maçã verde.',
    imageSource: require('../assets/home/prosecco.png'),
    wineSold: 126,
  },
  {
    wineName: 'Champagne',
    wineCategory: 'Espumante',
    winePrice: 'R$ 270,00',
    wineSigns: '4.9',
    ml: '750ml',
    wineDescription: 'Clássico espumante francês, com sabor complexo e final elegante.',
    imageSource: require('../assets/home/champagne.png'),
    wineSold: 65,
  },
];

export default Wines;
